### ISSUE TITLE
mountpoint /cloud already mounted

### ISSUE THREAD

**Issue by hazcod** [wiserain/docker-plexdrive#6]
After setting up plexdrive via the `exec` method:

```
plexdrive    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
plexdrive    | [s6-init] ensuring user provided files have correct perms...exited 0.
plexdrive    | [fix-attrs.d] applying ownership & permissions fixes...
plexdrive    | [fix-attrs.d] done.
plexdrive    | [cont-init.d] executing container initialization scripts...
plexdrive    | [cont-init.d] 10-adduser: executing... 
plexdrive    | 
plexdrive    | GID/UID
plexdrive    | -------------------------------------
plexdrive    | User uid:    911
plexdrive    | User gid:    911
plexdrive    | -------------------------------------
plexdrive    | 
plexdrive    | [cont-init.d] 10-adduser: exited 0.
plexdrive    | [cont-init.d] 40-config: executing... 
plexdrive    | [cont-init.d] 40-config: exited 0.
plexdrive    | [cont-init.d] 50-plexdrive: executing... 
plexdrive    | *** checking config
plexdrive    | Waiting for config files in /config. Retrying in 30s ...
plexdrive    | RUN: docker exec -it <CONTAINER_NAME> plexdrive_setup
plexdrive    | Waiting for config files in /config. Retrying in 30s ...
plexdrive    | RUN: docker exec -it <CONTAINER_NAME> plexdrive_setup
plexdrive    | Waiting for config files in /config. Retrying in 30s ...
plexdrive    | RUN: docker exec -it <CONTAINER_NAME> plexdrive_setup
plexdrive    | Waiting for config files in /config. Retrying in 30s ...
plexdrive    | RUN: docker exec -it <CONTAINER_NAME> plexdrive_setup
plexdrive    | *** checking mountpoint
plexdrive    | mountpoint (/cloud) already mounted. Retrying in 15s ...
plexdrive    | mountpoint (/cloud) already mounted. Retrying in 15s ...
plexdrive    | mountpoint (/cloud) already mounted. Retrying in 15s ...
```

compose:
```yaml
version: '3'

services:
  plexdrive:
    container_name: plexdrive
    image: wiserain/plexdrive:5.1.0
    restart: always
    network_mode: "bridge"
    volumes:
      - /home/parallels/plexdrive/config:/config
      - /home/parallels/plexdrive/cache:/cache
      - /home/parallels/cloud:/data:shared
    privileged: true
    devices:
      - /dev/fuse
    cap_add:
      - MKNOD
      - SYS_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels

```
